modLoader="javafml"
loaderVersion="[40,)"

license="All rights reserved"

[[mods]]
modId="marbledsarsenal"
version="2.4.0.0"
displayName="Marbled's Arsenal"
displayURL="https://www.curseforge.com/minecraft/mc-mods/marbleds-arsenal / https://modrinth.com/mod/marbledsarsenal" #optional
logoFile="ma_logo.png"
credits="MarbledHubb Studios"
authors="MarbledNull, WereF0X"

description='''A mod that adds modern militaristic armors and melee weapons.'''

[[dependencies.marbledsarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.marbledsarsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.marbledsarsenal]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.57,)"
    ordering="NONE"
    side="BOTH"