modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="marbledsarsenal"
version="2.4.0.0"
displayName="Marbled's Arsenal"
displayURL="https://www.curseforge.com/minecraft/mc-mods/marbleds-arsenal / https://modrinth.com/mod/marbledsarsenal"
logoFile="ma_logo.png"
credits="MarbledHubb Studios"
authors="MarbledNull, WereF0X"

description='''A mod that adds modern militaristic armors and melee weapons.'''

[[dependencies.marbledsarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.marbledsarsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"